class AppRoute<T> {
  final RouteType type;
  final T? args;
  const AppRoute({required this.type, this.args});
  String get title => type.title;
}

enum RouteType {
  dashboard,
  cashDesk,
  newSale,
  sales,
  purchases,
  saleReturns,
  purchaseReturns,
  inventory,
  products,
  warehouses,
  inventoryAdjustments,
  inventoryTransfers,
  waste,
  parties,
  partyDetails,
  customers,
  suppliers,
  cashboxes,
  cashboxDetails,
  expenses,
  cashTransfers,
  cashSessions,
  financialYears,
  reports,
  generalLedger,
  capital,
  closingAccounts,
  sync,
  organizationMembers,
  keyboardShortcuts,
  settings,
}

extension RouteTypeExtension on RouteType {
  String get title => switch (this) {
    RouteType.dashboard => 'لوحة التحكم',
    RouteType.cashDesk => 'الصندوق',
    RouteType.newSale => 'فاتورة بيع جديدة',
    RouteType.sales => 'المبيعات',
    RouteType.purchases => 'المشتريات',
    RouteType.saleReturns => 'مرتجعات البيع',
    RouteType.purchaseReturns => 'مرتجعات الشراء',
    RouteType.inventory => 'المخزون',
    RouteType.products => 'المنتجات',
    RouteType.warehouses => 'المستودعات',
    RouteType.inventoryAdjustments => 'الجرد والتسويات',
    RouteType.inventoryTransfers => 'تحويلات المستودعات',
    RouteType.waste => 'الهالك',
    RouteType.parties => 'الأطراف',
    RouteType.partyDetails => 'تفاصيل الطرف',
    RouteType.customers => 'العملاء',
    RouteType.suppliers => 'الموردون',
    RouteType.cashboxes => 'الصناديق',
    RouteType.cashboxDetails => 'تفاصيل الصندوق',
    RouteType.expenses => 'المصروفات',
    RouteType.cashTransfers => 'تحويلات الصندوق',
    RouteType.cashSessions => 'جلسات الصندوق',
    RouteType.financialYears => 'السنوات المالية',
    RouteType.reports => 'التقارير',
    RouteType.generalLedger => 'المحاسبة العامة',
    RouteType.capital => 'رأس المال والشركاء',
    RouteType.closingAccounts => 'الحسابات الختامية',
    RouteType.sync => 'المزامنة',
    RouteType.organizationMembers => 'أعضاء المؤسسة',
    RouteType.keyboardShortcuts => 'اختصارات لوحة المفاتيح',
    RouteType.settings => 'الإعدادات',
  };
}
