import 'package:accounting_system/core/providers/accounting_providers.dart';
import 'package:accounting_system/features/master_data/ui/product_details_dialog.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class ProductsScreen extends ConsumerStatefulWidget { const ProductsScreen({super.key}); @override ConsumerState<ProductsScreen> createState()=>_ProductsScreenState(); }
class _ProductsScreenState extends ConsumerState<ProductsScreen>{
 final search=TextEditingController(); @override void dispose(){search.dispose();super.dispose();}
 @override Widget build(BuildContext context){ref.watch(dataRevisionProvider);return Scaffold(appBar:AppBar(title:const Text('المنتجات')),floatingActionButton:FloatingActionButton(onPressed:_add,child:const Icon(Icons.add)),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'بحث عن منتج أو باركود')),const SizedBox(height:12),Expanded(child:FutureBuilder(future:ref.read(masterDataRepositoryProvider).listProducts(search:search.text),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final rows=s.data??[];return ListView.separated(itemCount:rows.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(c,i){final r=rows[i];return ListTile(leading:const Icon(Icons.inventory_2_outlined),title:Text('${r['name']}'),subtitle:Text('${r['category_name']??'بدون تصنيف'} • ${r['primary_unit_name']??''}'),onTap:()=>showDialog(context:context,builder:(_)=>ProductDetailsDialog(product:r)));});}))])));}
 Future<void> _add() async {final name=TextEditingController(),unit=TextEditingController(text:'قطعة'),barcode=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:const Text('منتج جديد'),content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'اسم المنتج')),const SizedBox(height:8),TextField(controller:unit,decoration:const InputDecoration(labelText:'الوحدة الرئيسية')),const SizedBox(height:8),TextField(controller:barcode,decoration:const InputDecoration(labelText:'الباركود (اختياري)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('حفظ'))]));if(ok==true&&name.text.trim().isNotEmpty){await ref.read(masterDataRepositoryProvider).createProduct(name:name.text,primaryUnitName:unit.text,barcode:barcode.text);ref.read(dataRevisionProvider.notifier).state++;}name.dispose();unit.dispose();barcode.dispose();}
}
