// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQX-0BQunoSkf_CvrnPL3YucvFJgrtTE',
    appId: '1:255849030942:web:2368f1c67a84d1873a950f',
    messagingSenderId: '255849030942',
    projectId: 'accountingsystem-7fb30',
    authDomain: 'accountingsystem-7fb30.firebaseapp.com',
    storageBucket: 'accountingsystem-7fb30.firebasestorage.app',
    measurementId: 'G-92SQ44T6J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FlZMTzyLFb7jfaaCEZSXNgYoe-VvfcA',
    appId: '1:255849030942:android:e36795992894e3f23a950f',
    messagingSenderId: '255849030942',
    projectId: 'accountingsystem-7fb30',
    storageBucket: 'accountingsystem-7fb30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYTfwpYd9jFc6EKVu4h0wS4JyTX3GxAQ4',
    appId: '1:255849030942:ios:e139082a816f87e53a950f',
    messagingSenderId: '255849030942',
    projectId: 'accountingsystem-7fb30',
    storageBucket: 'accountingsystem-7fb30.firebasestorage.app',
    iosBundleId: 'com.example.accountingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYTfwpYd9jFc6EKVu4h0wS4JyTX3GxAQ4',
    appId: '1:255849030942:ios:e139082a816f87e53a950f',
    messagingSenderId: '255849030942',
    projectId: 'accountingsystem-7fb30',
    storageBucket: 'accountingsystem-7fb30.firebasestorage.app',
    iosBundleId: 'com.example.accountingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQX-0BQunoSkf_CvrnPL3YucvFJgrtTE',
    appId: '1:255849030942:web:6743b2e6abc2d1c43a950f',
    messagingSenderId: '255849030942',
    projectId: 'accountingsystem-7fb30',
    authDomain: 'accountingsystem-7fb30.firebaseapp.com',
    storageBucket: 'accountingsystem-7fb30.firebasestorage.app',
    measurementId: 'G-GKK30JMMQF',
  );
}
