import 'package:accounting_system/core/db/app_database.dart';
import 'package:accounting_system/core/db/local_context.dart';
import 'package:accounting_system/core/providers/sync_providers.dart';
import 'package:accounting_system/core/providers/accounting_providers.dart';
import 'package:accounting_system/features/settings/domain/provider/setting_prov.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class SettingsScreen extends ConsumerWidget{const SettingsScreen({super.key});
 @override Widget build(BuildContext context,WidgetRef ref){final settings=ref.watch(settingsControllerProvider);final sync=ref.watch(syncStatusProvider);return Scaffold(appBar:AppBar(title:const Text('الإعدادات')),body:ListView(padding:const EdgeInsets.all(20),children:[Card(child:Column(children:[ListTile(title:const Text('اللغة'),trailing:DropdownButton<String>(value:settings.language,items:const [DropdownMenuItem(value:'ar',child:Text('العربية')),DropdownMenuItem(value:'en',child:Text('English'))],onChanged:(v){if(v!=null)ref.read(settingsControllerProvider.notifier).changeLanguage(v);})),ListTile(title:const Text('المظهر'),trailing:DropdownButton<ThemeMode>(value:settings.themeMode,items:const [DropdownMenuItem(value:ThemeMode.system,child:Text('تلقائي')),DropdownMenuItem(value:ThemeMode.light,child:Text('فاتح')),DropdownMenuItem(value:ThemeMode.dark,child:Text('داكن'))],onChanged:(v){if(v!=null)ref.read(settingsControllerProvider.notifier).changeTheme(v);})),])),const SizedBox(height:12),Card(child:sync.when(loading:()=>const ListTile(title:Text('المزامنة'),trailing:CircularProgressIndicator()),error:(e,_)=>ListTile(title:const Text('المزامنة'),subtitle:Text('$e')),data:(s)=>Column(children:[ListTile(title:const Text('حالة المزامنة'),subtitle:Text((s['backend_configured'] as bool)?'جاهزة':'Backend غير مربوط بعد'),trailing:Chip(label:Text('${s['pending']} معلّق • ${s['conflicts']??0} تعارض'))),ListTile(title:const Text('مزامنة الآن'),subtitle:Text('آخر مزامنة: ${s['last_sync_at']??'—'}'),trailing:const Icon(Icons.sync),onTap:()async{try{await ref.read(syncEngineProvider).syncNow();}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}ref.invalidate(syncStatusProvider);})]))),const SizedBox(height:12),Card(child:ListTile(leading:const Icon(Icons.delete_forever),title:const Text('حذف قاعدة البيانات المحلية'),subtitle:const Text('للتطوير فقط. يحذف كل البيانات المحلية.'),onTap:()async{final ok=await showDialog<bool>(context:context,builder:(x)=>AlertDialog(title:const Text('تأكيد الحذف'),content:const Text('هل أنت متأكد؟'),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('حذف'))]));if(ok==true){await AppDatabase.instance.deleteDB();LocalContextService.instance.clearCache();ref.invalidate(localContextProvider);ref.read(dataRevisionProvider.notifier).state++;}}))]));}
}
