import 'package:accounting_system/core/providers/accounting_providers.dart';
import 'package:accounting_system/features/inventory/data/inventory_repository.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

enum InventoryActionMode{adjustment,transfer}
class InventoryActionScreen extends ConsumerWidget{const InventoryActionScreen({super.key,required this.mode});final InventoryActionMode mode;
 @override Widget build(BuildContext context,WidgetRef ref){ref.watch(dataRevisionProvider);return Scaffold(appBar:AppBar(title:Text(mode==InventoryActionMode.adjustment?'الجرد والتسويات':'تحويلات المستودعات')),floatingActionButton:FloatingActionButton(onPressed:()=>mode==InventoryActionMode.adjustment?_adjust(context,ref):_transfer(context,ref),child:const Icon(Icons.add)),body:FutureBuilder(future:mode==InventoryActionMode.adjustment?ref.read(inventoryRepositoryProvider).movementHistory():ref.read(inventoryRepositoryProvider).movementHistory(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());final rows=s.data??[];final filtered=rows.where((r)=>mode==InventoryActionMode.adjustment?r['movement_type']=='adjustment':(r['movement_type']=='transfer_in'||r['movement_type']=='transfer_out')).toList();return ListView.builder(padding:const EdgeInsets.all(20),itemCount:filtered.length,itemBuilder:(c,i){final r=filtered[i];return Card(child:ListTile(title:Text('${r['product_name']}'),subtitle:Text('${r['movement_type']} • ${r['warehouse_name']}'),trailing:Text('${r['quantity_delta']}')));});}));}
 Future<void> _adjust(BuildContext context,WidgetRef ref) async {final inv=await ref.read(inventoryRepositoryProvider).listInventory();if(!context.mounted)return;if(inv.isEmpty)return;String id=inv.first['inventory_item_id'] as String;final q=TextEditingController(text:'${inv.first['current_quantity']}');final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setL)=>AlertDialog(title:const Text('تسوية مخزون'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:id,items:inv.map((e)=>DropdownMenuItem(value:e['inventory_item_id'] as String,child:Text('${e['product_name']} - ${e['warehouse_name']}'))).toList(),onChanged:(v){if(v!=null){setL(()=>id=v);final r=inv.firstWhere((e)=>e['inventory_item_id']==v);q.text='${r['current_quantity']}';}},decoration:const InputDecoration(labelText:'الصنف')),const SizedBox(height:8),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الكمية المعدودة'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('اعتماد'))])));if(ok==true){final r=inv.firstWhere((e)=>e['inventory_item_id']==id);await ref.read(inventoryRepositoryProvider).postAdjustment(warehouseId:r['warehouse_id'] as String,items:[InventoryAdjustmentInput(inventoryItemId:id,productUnitId:r['primary_unit_id'] as String,countedQuantity:double.parse(q.text))]);ref.read(dataRevisionProvider.notifier).state++;}q.dispose();}
 Future<void> _transfer(BuildContext context,WidgetRef ref) async {final inv=await ref.read(inventoryRepositoryProvider).listInventory();final wh=await ref.read(masterDataRepositoryProvider).listWarehouses();if(!context.mounted||inv.isEmpty||wh.length<2)return;String itemId=inv.first['inventory_item_id'] as String;String from=inv.first['warehouse_id'] as String;String to=wh.firstWhere((w)=>w['id']!=from)['id'] as String;final q=TextEditingController(text:'1');final ok=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setL)=>AlertDialog(title:const Text('تحويل مخزون'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:itemId,items:inv.map((e)=>DropdownMenuItem(value:e['inventory_item_id'] as String,child:Text('${e['product_name']} - ${e['warehouse_name']}'))).toList(),onChanged:(v){if(v!=null){final r=inv.firstWhere((e)=>e['inventory_item_id']==v);setL((){itemId=v;from=r['warehouse_id'] as String;to=wh.firstWhere((w)=>w['id']!=from)['id'] as String;});}},decoration:const InputDecoration(labelText:'الصنف')),const SizedBox(height:8),DropdownButtonFormField<String>(value:to,items:wh.where((w)=>w['id']!=from).map((w)=>DropdownMenuItem(value:w['id'] as String,child:Text('${w['name']}'))).toList(),onChanged:(v){if(v!=null)setL(()=>to=v);},decoration:const InputDecoration(labelText:'إلى مستودع')),const SizedBox(height:8),TextField(controller:q,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الكمية'))]),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('تحويل'))])));if(ok==true){final r=inv.firstWhere((e)=>e['inventory_item_id']==itemId);await ref.read(inventoryRepositoryProvider).postTransfer(fromWarehouseId:from,toWarehouseId:to,items:[InventoryTransferInput(productId:r['product_id'] as String,productUnitId:r['primary_unit_id'] as String,quantity:double.parse(q.text),unitFactor:1)]);ref.read(dataRevisionProvider.notifier).state++;}q.dispose();}
}
