import 'package:accounting_system/core/providers/accounting_providers.dart';
import 'package:accounting_system/core/domain/money.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class InventoryScreen extends ConsumerStatefulWidget{const InventoryScreen({super.key});@override ConsumerState<InventoryScreen> createState()=>_InventoryScreenState();}
class _InventoryScreenState extends ConsumerState<InventoryScreen>{final search=TextEditingController();@override void dispose(){search.dispose();super.dispose();}
 @override Widget build(BuildContext context){ref.watch(dataRevisionProvider);final currency=ref.watch(localContextProvider).asData?.value?.currencyCode??'USD';return Scaffold(appBar:AppBar(title:const Text('المخزون')),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Row(children:[Expanded(child:TextField(controller:search,onChanged:(_)=>setState((){}),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'بحث بالمخزون'))),const SizedBox(width:10),FilledButton.icon(onPressed:_opening,icon:const Icon(Icons.add),label:const Text('رصيد افتتاحي'))]),const SizedBox(height:12),Expanded(child:FutureBuilder(future:ref.read(inventoryRepositoryProvider).listInventory(search:search.text),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('${s.error}'));final rows=s.data??[];if(rows.isEmpty)return const Center(child:Text('لا توجد أرصدة مخزون بعد. أضف منتجاً ثم رصيداً افتتاحياً.'));return ListView.separated(itemCount:rows.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(c,i){final r=rows[i];return ListTile(title:Text('${r['product_name']}'),subtitle:Text('${r['warehouse_name']} • ${r['primary_unit_name']??''}'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text('${r['current_quantity']}'),Text(Money((r['inventory_value_minor'] as num).toInt()).format(locale:Localizations.localeOf(context).toString(),currencyCode:currency),style:Theme.of(context).textTheme.bodySmall)]));});}))])));}
 Future<void> _opening() async {final products=await ref.read(masterDataRepositoryProvider).listProducts();final warehouses=await ref.read(masterDataRepositoryProvider).listWarehouses();if(!mounted)return;if(products.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('أنشئ منتجاً أولاً')));return;}String productId=products.first['id'] as String;String warehouseId=warehouses.first['id'] as String;final qty=TextEditingController(),value=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>AlertDialog(title:const Text('رصيد افتتاحي'),content:SizedBox(width:430,child:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(value:productId,items:products.map((p)=>DropdownMenuItem(value:p['id'] as String,child:Text('${p['name']}'))).toList(),onChanged:(v){if(v!=null)setLocal(()=>productId=v);},decoration:const InputDecoration(labelText:'المنتج')),const SizedBox(height:8),DropdownButtonFormField<String>(value:warehouseId,items:warehouses.map((p)=>DropdownMenuItem(value:p['id'] as String,child:Text('${p['name']}'))).toList(),onChanged:(v){if(v!=null)setLocal(()=>warehouseId=v);},decoration:const InputDecoration(labelText:'المستودع')),const SizedBox(height:8),TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'الكمية')),const SizedBox(height:8),TextField(controller:value,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'إجمالي قيمة المخزون'))])),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('اعتماد'))])));if(ok==true){await ref.read(inventoryRepositoryProvider).addOpeningBalance(productId:productId,warehouseId:warehouseId,quantity:double.parse(qty.text),totalValueMinor:Money.fromMajor(value.text));ref.read(dataRevisionProvider.notifier).state++;}qty.dispose();value.dispose();}
}
